### PR TITLE
bump: Minimum Java version required for build

### PR DESCRIPTION
**Pull request by hsinn0**
- From 11 to 17

[#186054022]

_Approve but do not merge. I will merge the change along with other bump change later._

### CODE REVIEW

**Review by peterhaochen47 — APPROVED** [review]

**Review by peterhaochen47 — APPROVED** [review]

**Comment by Tallicia** [comment]
It looks like there is a change in default precision causing the test failure: 

```
org.cloudfoundry.credhub.services.CertificateDataServiceTest > findAllValidMetadata when certificate is in 'names' returns certificates FAILED
    java.lang.AssertionError: expected:<2023-11-03T13:12:18.262579988Z> but was:<2023-11-03T13:12:18.262580Z>
```

**Comment by hsinn0** [comment]
> It looks like there is a change in default precision causing the test failure:
> 
> 262579988Z != 262580Z

Hmm, I am not sure why I did not run into the same failure when I ran the test locally.

**Comment by hsinn0** [comment]
> > It looks like there is a change in default precision causing the test failure:
> > 262579988Z != 262580Z
> 
> Hmm, I am not sure why I did not run into the same failure when I ran the test locally.

It is platform-dependent, e.g. Instant.now() return value precisions in my my Mac and linux are different.

**Review by Tallicia — APPROVED** [review]
LGTM

**Pull request merged**
